openapi: 3.2.0
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Root Cause Analysis Model API
tags:
- name: RootCauseAnalysisModel
paths:
  /rootCauseAnalysis/instances/{instanceId}/models/{modelId}:
    put:
      tags:
      - RootCauseAnalysisModel
      summary: Microsoft Azure Create A Training Model For Root Cause Analysis
      operationId: microsoftAzureCreaterootcauseanalysistrainingtask
      parameters:
      - in: path
        name: instanceId
        description: Instance unique id, should be a string of uuid
        required: true
        schema:
          type: string
          format: uuid
      - in: path
        name: modelId
        description: Model unique id, should be a string of uuid
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '201':
          description: Success
          headers:
            Location:
              description: Location of the newly created resource.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RootCauseAnalysisTrainingResponse'
              example:
                taskId: 11111111-1111-4444-4444-000000000000
                instanceId: 11111111-2222-3333-4444-000000000000
                modelId: 11223344-5555-6666-7777-000000000000
                displayName: Sample Root Cause Analysis Model Name
                kind: multidimensional
                status: scheduled
                createdDateTime: '2021-12-01T00:00:00Z'
                lastModifiedDateTime: '2021-12-01T00:00:00Z'
                parameter:
                  startDateTime: '2021-05-01T00:00:00Z'
                  endDateTime: '2021-09-01T00:00:00Z'
        default:
          description: Client error or server error (4xx or 5xx)
          headers:
            x-ms-error-code:
              description: error code
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'
      x-ms-examples:
        Create a training model for root cause analysis:
          $ref: ./examples/CreateRootCauseAnalysisTrainingTask.json
      description: Needs a more full description created.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RootCauseAnalysisTrainingRequest'
        required: true
    delete:
      tags:
      - RootCauseAnalysisModel
      summary: Microsoft Azure Delete A Model For Root Cause Analysis
      operationId: microsoftAzureDeleterootcauseanalysismodel
      parameters:
      - in: path
        name: instanceId
        description: Instance unique id, should be a string of uuid.
        required: true
        schema:
          type: string
          format: uuid
      - in: path
        name: modelId
        description: Model unique id, should be a string of uuid.
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '204':
          description: The resource is deleted successfully or does not exist.
        default:
          description: Client error or server error (4xx or 5xx)
          headers:
            x-ms-error-code:
              description: error code
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'
      x-ms-examples:
        Delete a model for root cause analysis:
          $ref: ./examples/DeleteRootCauseAnalysisModel.json
      description: Needs a more full description created.
    get:
      tags:
      - RootCauseAnalysisModel
      summary: Microsoft Azure Query A Training Task State For Root Cause Analysis
      operationId: microsoftAzureGetrootcauseanalysistrainingstate
      parameters:
      - in: path
        name: instanceId
        description: Instance unique id, should be a string of uuid.
        required: true
        schema:
          type: string
          format: uuid
      - in: path
        name: modelId
        description: Model unique id, should be a string of uuid.
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RootCauseAnalysisTrainingResponse'
        default:
          description: Client error or server error (4xx or 5xx)
          headers:
            x-ms-error-code:
              description: error code
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'
      x-ms-examples:
        Query a training task state for root cause analysis:
          $ref: ./examples/GetRootCauseAnalysisTrainingState.json
      description: Needs a more full description created.
  /rootCauseAnalysis/instances/{instanceId}/models:
    get:
      tags:
      - RootCauseAnalysisModel
      summary: Microsoft Azure Query Training Task State List For Root Cause Analysis
      operationId: microsoftAzureListrootcauseanalysistrainingstates
      parameters:
      - in: path
        name: instanceId
        description: Instance unique id, should be a string of uuid.
        required: true
        schema:
          type: string
          format: uuid
      - in: query
        name: skip
        description: For paging, skipped number
        schema:
          type: integer
          format: int32
      - in: query
        name: maxpagesize
        description: The maximum number of items in one page
        schema:
          type: integer
          format: int32
      - in: query
        name: filter
        description: The filter expression filters out the resources to be returned, currently contains(displayName, 'filter name’) is supported
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RootCauseAnalysisTrainingResponseList'
        default:
          description: Client error or server error (4xx or 5xx)
          headers:
            x-ms-error-code:
              description: error code
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-examples:
        Query training task state list for root cause analysis:
          $ref: ./examples/ListRootCauseAnalysisTrainingStates.json
      description: Needs a more full description created.
  /rootCauseAnalysis/instances/{instanceId}/models/{modelId}/inferences/{inferenceId}:
    put:
      tags:
      - RootCauseAnalysisModel
      summary: Microsoft Azure Create An Inference Task For Root Cause Analysis
      operationId: microsoftAzureCreaterootcauseanalysisinferencetask
      parameters:
      - in: path
        name: instanceId
        description: Instance unique id, should be a string of uuid.
        required: true
        schema:
          type: string
          format: uuid
      - in: path
        name: modelId
        description: Model unique id, should be a string of uuid.
        required: true
        schema:
          type: string
          format: uuid
      - in: path
        name: inferenceId
        description: Inference unique id, should be a string of uuid.
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '201':
          description: Success
          headers:
            Location:
              description: Location of the newly created resource.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RootCauseAnalysisInferenceResponse'
              example:
                inferenceId: 11111111-1111-1111-1111-000000000000
                instanceId: 11111111-2222-3333-4444-000000000000
                modelId: 11223344-5555-6666-7777-000000000000
                kind: multidimensional
                status: scheduled
                createdDateTime: '2021-12-01T00:00:00Z'
                lastModifiedDateTime: '2021-12-01T00:00:00Z'
                parameter:
                  timestamp: '2021-06-04T00:00:00Z'
                  dimensionScope: {}
        default:
          description: Client error or server error (4xx or 5xx)
          headers:
            x-ms-error-code:
              description: error code
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'
      x-ms-examples:
        Create an inference task for root cause analysis:
          $ref: ./examples/CreateRootCauseAnalysisInferenceTask.json
      description: Needs a more full description created.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RootCauseAnalysisInferenceRequest'
        description: Inference request of root cause analysis
        required: true
    get:
      tags:
      - RootCauseAnalysisModel
      summary: Microsoft Azure Query An Inference Task State For Root Cause Analysis
      operationId: microsoftAzureGetrootcauseanalysisinferencestate
      parameters:
      - in: path
        name: instanceId
        description: Instance unique id, should be a string of uuid.
        required: true
        schema:
          type: string
          format: uuid
      - in: path
        name: modelId
        description: Model unique id, should be a string of uuid.
        required: true
        schema:
          type: string
          format: uuid
      - in: path
        name: inferenceId
        description: Inference unique id, should be a string of uuid.
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RootCauseAnalysisInferenceResponse'
        default:
          description: Client error or server error (4xx or 5xx)
          headers:
            x-ms-error-code:
              description: error code
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'
      x-ms-examples:
        Query an inference task state for root cause analysis:
          $ref: ./examples/GetRootCauseAnalysisInferenceState.json
      description: Needs a more full description created.
components:
  schemas:
    RootCauseAnalysisTrainingRequest:
      required:
      - displayName
      - kind
      - parameter
      type: object
      properties:
        displayName:
          description: Model display name
          type: string
        kind:
          description: Root cause analysis kind
          enum:
          - multidimensional
          type: string
          x-ms-enum:
            name: RootCauseAnalysisType
            modelAsString: true
        parameter:
          description: Parameter for training
      example:
        displayName: Sample Root Cause Analysis Model Name
        kind: multidimensional
        parameter:
          startDateTime: '2021-05-01T00:00:00Z'
          endDateTime: '2021-09-01T00:00:00Z'
    RootCauseAnalysisTrainingResponseList:
      required:
      - value
      type: object
      properties:
        nextLink:
          description: Link of next page, only provided when there are next pages
          type: string
        value:
          description: Response values
          type: array
          items:
            $ref: '#/components/schemas/RootCauseAnalysisTrainingResponse'
    ErrorDetail:
      type: object
      properties:
        message:
          description: Human-readable error message
          type: string
        code:
          description: Error code
          type: string
    RootCauseAnalysisInferenceRequest:
      required:
      - kind
      - parameter
      type: object
      properties:
        kind:
          description: Root cause analysis kind
          enum:
          - multidimensional
          type: string
          x-ms-enum:
            name: RootCauseAnalysisType
            modelAsString: true
        parameter:
          description: Parameter for inference
      example:
        kind: multidimensional
        parameter:
          timestamp: '2021-06-04T00:00:00Z'
          dimensionScope: {}
    RootCauseAnalysisTrainingResponse:
      required:
      - createdDateTime
      - displayName
      - instanceId
      - kind
      - lastModifiedDateTime
      - modelId
      - status
      - taskId
      type: object
      properties:
        taskId:
          format: uuid
          description: Training task unique id for root cause analysis
          type: string
        instanceId:
          format: uuid
          description: Instance unique id for root cause analysis
          type: string
        modelId:
          format: uuid
          description: Model unique id for root cause analysis
          type: string
        displayName:
          description: Model name for root cause analysis
          type: string
        kind:
          description: kind of root cause analysis
          enum:
          - multidimensional
          type: string
          x-ms-enum:
            name: RootCauseAnalysisType
            modelAsString: true
        status:
          description: Training task status for root cause analysis
          enum:
          - scheduled
          - running
          - succeeded
          - failed
          - canceled
          type: string
          x-ms-enum:
            name: RootCauseAnalysisTrainingStatus
            modelAsString: true
        createdDateTime:
          format: date-time
          description: Training task created date time (UTC)
          type: string
        lastModifiedDateTime:
          format: date-time
          description: Training task state modified date time (UTC)
          type: string
        error:
          $ref: '#/components/schemas/ErrorDetail'
        taskInfo:
          description: Training task information, if status is failed, this failed will not be shown
        parameter:
          description: Root cause analysis training parameter
    RootCauseAnalysisInferenceResponse:
      required:
      - createdDateTime
      - inferenceId
      - instanceId
      - kind
      - lastModifiedDateTime
      - modelId
      - status
      type: object
      properties:
        inferenceId:
          format: uuid
          description: Inference unique id for root cause analysis
          type: string
        instanceId:
          format: uuid
          description: Instance unique id for root cause analysis
          type: string
        modelId:
          format: uuid
          description: Model unique id for root cause analysis
          type: string
        kind:
          description: Kind of root cause analysis
          enum:
          - multidimensional
          type: string
          x-ms-enum:
            name: RootCauseAnalysisType
            modelAsString: true
        status:
          description: Inference task status for root cause analysis
          enum:
          - scheduled
          - running
          - succeeded
          - failed
          - canceled
          type: string
          x-ms-enum:
            name: RootCauseAnalysisInferenceStatus
            modelAsString: true
        createdDateTime:
          format: date-time
          description: Inference task created date time (UTC)
          type: string
        lastModifiedDateTime:
          format: date-time
          description: Inference task state last modified date time (UTC)
          type: string
        error:
          $ref: '#/components/schemas/ErrorDetail'
        result:
          description: Root cause analysis inference result, if status is failed, this field wil not be shown
        parameter:
          description: Root cause analysis inference parameter
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/components/parameters/Endpoint'
