swagger: '2.0'
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Containers API
  description: Operations on blob containers
schemes:
- https
tags:
- name: Containers
  description: Operations on blob containers
paths:
  /{containerName}:
    put:
      operationId: Container_Create
      summary: Microsoft Azure Create a Container
      description: Creates a new container under the specified account. If the container with the same name already exists, the operation fails.
      tags:
      - Containers
      parameters:
      - $ref: '#/components/parameters/ContainerNameParameter'
      - name: restype
        in: query
        required: true
        schema:
          type: string
          enum:
          - container
        example: container
      - $ref: '#/components/parameters/ApiVersionParameter'
      - name: x-ms-blob-public-access
        in: header
        description: Specifies whether data in the container may be accessed publicly.
        schema:
          type: string
          enum:
          - container
          - blob
        example: container
      - name: x-ms-meta
        in: header
        description: Name-value pairs to associate with the container as metadata.
        schema:
          type: string
        example: example_value
      responses:
        '201':
          description: Successfully created the container.
          headers:
            ETag:
              schema:
                type: string
              description: The ETag for the container.
            Last-Modified:
              schema:
                type: string
                format: date-time-rfc1123
              description: The date/time that the container was last modified.
        '409':
          description: The container already exists.
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/StorageError'
              examples:
                ContainerCreate409Example:
                  summary: Default Container_Create 409 response
                  x-microcks-default: true
                  value:
                    Code: example_value
                    Message: example_value
                    AuthenticationErrorDetail: example_value
        default:
          description: An error occurred.
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/StorageError'
              examples:
                ContainerCreatedefaultExample:
                  summary: Default Container_Create default response
                  x-microcks-default: true
                  value:
                    Code: example_value
                    Message: example_value
                    AuthenticationErrorDetail: example_value
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    get:
      operationId: Container_ListBlobs
      summary: Microsoft Azure List Blobs in a Container
      description: Returns a list of the blobs under the specified container.
      tags:
      - Containers
      parameters:
      - $ref: '#/components/parameters/ContainerNameParameter'
      - name: restype
        in: query
        required: true
        schema:
          type: string
          enum:
          - container
        example: container
      - name: comp
        in: query
        required: true
        schema:
          type: string
          enum:
          - list
        example: list
      - $ref: '#/components/parameters/ApiVersionParameter'
      - name: prefix
        in: query
        description: Filters the results to return only blobs whose name begins with the specified prefix.
        schema:
          type: string
        example: example_value
      - name: delimiter
        in: query
        description: Filters the results to return only blobs with names up to the specified delimiter.
        schema:
          type: string
        example: example_value
      - name: marker
        in: query
        description: A string value that identifies the portion of the list to be returned.
        schema:
          type: string
        example: example_value
      - name: maxresults
        in: query
        description: Maximum number of blobs to return.
        schema:
          type: integer
          minimum: 1
          maximum: 5000
        example: 10
      - name: include
        in: query
        description: 'Specifies one or more datasets to include in the response: snapshots, metadata, uncommittedblobs, copy, deleted, tags, versions, deletedwithversions, immutabilitypolicy, legalhold, permissions.'
        schema:
          type: string
        example: example_value
      responses:
        '200':
          description: Successfully listed the blobs.
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/BlobEnumerationResults'
              examples:
                ContainerListblobs200Example:
                  summary: Default Container_ListBlobs 200 response
                  x-microcks-default: true
                  value:
                    ServiceEndpoint: example_value
                    ContainerName: example_value
                    Prefix: example_value
                    Marker: example_value
                    MaxResults: 10
                    Blobs:
                      Blob:
                      - {}
                      BlobPrefix:
                      - Name: Example Title
                    NextMarker: example_value
        default:
          description: An error occurred.
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/StorageError'
              examples:
                ContainerListblobsdefaultExample:
                  summary: Default Container_ListBlobs default response
                  x-microcks-default: true
                  value:
                    Code: example_value
                    Message: example_value
                    AuthenticationErrorDetail: example_value
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    delete:
      operationId: Container_Delete
      summary: Microsoft Azure Delete a Container
      description: Marks the specified container for deletion. The container and any blobs within it are later deleted.
      tags:
      - Containers
      parameters:
      - $ref: '#/components/parameters/ContainerNameParameter'
      - name: restype
        in: query
        required: true
        schema:
          type: string
          enum:
          - container
        example: container
      - $ref: '#/components/parameters/ApiVersionParameter'
      - name: x-ms-lease-id
        in: header
        description: Required if the container has an active lease.
        schema:
          type: string
        example: '500123'
      responses:
        '202':
          description: The container has been marked for deletion.
        default:
          description: An error occurred.
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/StorageError'
              examples:
                ContainerDeletedefaultExample:
                  summary: Default Container_Delete default response
                  x-microcks-default: true
                  value:
                    Code: example_value
                    Message: example_value
                    AuthenticationErrorDetail: example_value
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /dbs/{databaseId}/colls:
    get:
      operationId: Containers_List
      summary: Microsoft Azure List Containers
      description: Returns a list of containers under the specified database.
      tags:
      - Containers
      parameters:
      - $ref: '#/components/parameters/DatabaseIdParameter'
      - $ref: '#/components/parameters/ApiVersionParameter_2'
      - $ref: '#/components/parameters/MaxItemCountParameter'
      - $ref: '#/components/parameters/ContinuationParameter'
      responses:
        '200':
          description: Successfully returned the list of containers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContainerListResult'
              examples:
                ContainersList200Example:
                  summary: Default Containers_List 200 response
                  x-microcks-default: true
                  value:
                    _rid: '500123'
                    DocumentCollections:
                    - id: abc123
                      defaultTtl: 10
                      _rid: '500123'
                      _ts: 10
                      _self: example_value
                      _etag: example_value
                      _docs: example_value
                      _sprocs: example_value
                      _triggers: example_value
                      _udfs: example_value
                    _count: 10
        default:
          description: Error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                ContainersListdefaultExample:
                  summary: Default Containers_List default response
                  x-microcks-default: true
                  value:
                    code: example_value
                    message: example_value
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    post:
      operationId: Containers_Create
      summary: Microsoft Azure Create a Container
      description: Creates a new container under the specified database.
      tags:
      - Containers
      parameters:
      - $ref: '#/components/parameters/DatabaseIdParameter'
      - $ref: '#/components/parameters/ApiVersionParameter_2'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContainerCreateRequest'
            examples:
              ContainersCreateRequestExample:
                summary: Default Containers_Create request
                x-microcks-default: true
                value:
                  id: abc123
                  indexingPolicy:
                    automatic: true
                    indexingMode: consistent
                    includedPaths:
                    - {}
                    excludedPaths:
                    - {}
                    compositeIndexes:
                    - {}
                    spatialIndexes:
                    - {}
                  partitionKey:
                    paths:
                    - {}
                    kind: Hash
                    version: 1
                  uniqueKeyPolicy:
                    uniqueKeys:
                    - {}
                  conflictResolutionPolicy:
                    mode: LastWriterWins
                    conflictResolutionPath: example_value
                    conflictResolutionProcedure: example_value
                  defaultTtl: 10
      responses:
        '201':
          description: Successfully created the container.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Container'
              examples:
                ContainersCreate201Example:
                  summary: Default Containers_Create 201 response
                  x-microcks-default: true
                  value:
                    id: abc123
                    indexingPolicy:
                      automatic: true
                      indexingMode: consistent
                      includedPaths:
                      - {}
                      excludedPaths:
                      - {}
                      compositeIndexes:
                      - {}
                      spatialIndexes:
                      - {}
                    partitionKey:
                      paths:
                      - {}
                      kind: Hash
                      version: 1
                    uniqueKeyPolicy:
                      uniqueKeys:
                      - {}
                    conflictResolutionPolicy:
                      mode: LastWriterWins
                      conflictResolutionPath: example_value
                      conflictResolutionProcedure: example_value
                    defaultTtl: 10
                    _rid: '500123'
                    _ts: 10
                    _self: example_value
                    _etag: example_value
                    _docs: example_value
                    _sprocs: example_value
                    _triggers: example_value
                    _udfs: example_value
        '409':
          description: The container with the specified ID already exists.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                ContainersCreate409Example:
                  summary: Default Containers_Create 409 response
                  x-microcks-default: true
                  value:
                    code: example_value
                    message: example_value
        default:
          description: Error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                ContainersCreatedefaultExample:
                  summary: Default Containers_Create default response
                  x-microcks-default: true
                  value:
                    code: example_value
                    message: example_value
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  /dbs/{databaseId}/colls/{containerId}:
    get:
      operationId: Containers_Get
      summary: Microsoft Azure Get a Container
      description: Retrieves a container resource by its ID.
      tags:
      - Containers
      parameters:
      - $ref: '#/components/parameters/DatabaseIdParameter'
      - $ref: '#/components/parameters/ContainerIdParameter'
      - $ref: '#/components/parameters/ApiVersionParameter_2'
      responses:
        '200':
          description: Successfully returned the container.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Container'
              examples:
                ContainersGet200Example:
                  summary: Default Containers_Get 200 response
                  x-microcks-default: true
                  value:
                    id: abc123
                    indexingPolicy:
                      automatic: true
                      indexingMode: consistent
                      includedPaths:
                      - {}
                      excludedPaths:
                      - {}
                      compositeIndexes:
                      - {}
                      spatialIndexes:
                      - {}
                    partitionKey:
                      paths:
                      - {}
                      kind: Hash
                      version: 1
                    uniqueKeyPolicy:
                      uniqueKeys:
                      - {}
                    conflictResolutionPolicy:
                      mode: LastWriterWins
                      conflictResolutionPath: example_value
                      conflictResolutionProcedure: example_value
                    defaultTtl: 10
                    _rid: '500123'
                    _ts: 10
                    _self: example_value
                    _etag: example_value
                    _docs: example_value
                    _sprocs: example_value
                    _triggers: example_value
                    _udfs: example_value
        default:
          description: Error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                ContainersGetdefaultExample:
                  summary: Default Containers_Get default response
                  x-microcks-default: true
                  value:
                    code: example_value
                    message: example_value
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    put:
      operationId: Containers_Replace
      summary: Microsoft Azure Replace a Container
      description: Replaces the entire container resource.
      tags:
      - Containers
      parameters:
      - $ref: '#/components/parameters/DatabaseIdParameter'
      - $ref: '#/components/parameters/ContainerIdParameter'
      - $ref: '#/components/parameters/ApiVersionParameter_2'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContainerCreateRequest'
            examples:
              ContainersReplaceRequestExample:
                summary: Default Containers_Replace request
                x-microcks-default: true
                value:
                  id: abc123
                  indexingPolicy:
                    automatic: true
                    indexingMode: consistent
                    includedPaths:
                    - {}
                    excludedPaths:
                    - {}
                    compositeIndexes:
                    - {}
                    spatialIndexes:
                    - {}
                  partitionKey:
                    paths:
                    - {}
                    kind: Hash
                    version: 1
                  uniqueKeyPolicy:
                    uniqueKeys:
                    - {}
                  conflictResolutionPolicy:
                    mode: LastWriterWins
                    conflictResolutionPath: example_value
                    conflictResolutionProcedure: example_value
                  defaultTtl: 10
      responses:
        '200':
          description: Successfully replaced the container.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Container'
              examples:
                ContainersReplace200Example:
                  summary: Default Containers_Replace 200 response
                  x-microcks-default: true
                  value:
                    id: abc123
                    indexingPolicy:
                      automatic: true
                      indexingMode: consistent
                      includedPaths:
                      - {}
                      excludedPaths:
                      - {}
                      compositeIndexes:
                      - {}
                      spatialIndexes:
                      - {}
                    partitionKey:
                      paths:
                      - {}
                      kind: Hash
                      version: 1
                    uniqueKeyPolicy:
                      uniqueKeys:
                      - {}
                    conflictResolutionPolicy:
                      mode: LastWriterWins
                      conflictResolutionPath: example_value
                      conflictResolutionProcedure: example_value
                    defaultTtl: 10
                    _rid: '500123'
                    _ts: 10
                    _self: example_value
                    _etag: example_value
                    _docs: example_value
                    _sprocs: example_value
                    _triggers: example_value
                    _udfs: example_value
        default:
          description: Error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                ContainersReplacedefaultExample:
                  summary: Default Containers_Replace default response
                  x-microcks-default: true
                  value:
                    code: example_value
                    message: example_value
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
    delete:
      operationId: Containers_Delete
      summary: Microsoft Azure Delete a Container
      description: Deletes a container and all contained items.
      tags:
      - Containers
      parameters:
      - $ref: '#/components/parameters/DatabaseIdParameter'
      - $ref: '#/components/parameters/ContainerIdParameter'
      - $ref: '#/components/parameters/ApiVersionParameter_2'
      responses:
        '204':
          description: Successfully deleted the container.
        default:
          description: Error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                ContainersDeletedefaultExample:
                  summary: Default Containers_Delete default response
                  x-microcks-default: true
                  value:
                    code: example_value
                    message: example_value
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataBoxEdge/dataBoxEdgeDevices/{deviceName}/storageAccounts/{storageAccountName}/containers
  : get:
      tags:
      - Containers
      summary: Microsoft Azure Lists All The Containers Of A Storage Account In A Data Box Edge Data Box Gateway Device
      operationId: microsoftAzureContainersListbystorageaccount
      parameters:
      - name: deviceName
        in: path
        description: The device name.
        required: true
        type: string
      - name: storageAccountName
        in: path
        description: The storage Account name.
        required: true
        type: string
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/resourceGroupNameParameter'
      - $ref: '#/parameters/apiVersionParameter'
      responses:
        '200':
          description: The collection of all the containers on the device.
          schema:
            $ref: '#/definitions/ContainerList'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-pageable:
        nextLinkName: nextLink
      x-ms-examples:
        ContainerListAllInDevice:
          $ref: ./examples/ContainerListAllInDevice.json
      description: Needs a more full description created.
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataBoxEdge/dataBoxEdgeDevices/{deviceName}/storageAccounts/{storageAccountName}/containers/{containerName}
  : get:
      tags:
      - Containers
      summary: Microsoft Azure Gets A Container By Name
      operationId: microsoftAzureContainersGet
      parameters:
      - name: deviceName
        in: path
        description: The device name.
        required: true
        type: string
      - name: storageAccountName
        in: path
        description: The Storage Account Name
        required: true
        type: string
      - name: containerName
        in: path
        description: The container Name
        required: true
        type: string
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/resourceGroupNameParameter'
      - $ref: '#/parameters/apiVersionParameter'
      responses:
        '200':
          description: The container details.
          schema:
            $ref: '#/definitions/Container'
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-examples:
        ContainerGet:
          $ref: ./examples/ContainerGet.json
      description: Needs a more full description created.
    put:
      tags:
      - Containers
      summary: Microsoft Azure Creates A New Container Or Updates An Existing Container On The Device
      operationId: microsoftAzureContainersCreateorupdate
      parameters:
      - name: deviceName
        in: path
        description: The device name.
        required: true
        type: string
      - name: storageAccountName
        in: path
        description: The Storage Account Name
        required: true
        type: string
      - name: containerName
        in: path
        description: The container name.
        required: true
        type: string
      - name: container
        in: body
        description: The container properties.
        required: true
        schema:
          $ref: '#/definitions/Container'
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/resourceGroupNameParameter'
      - $ref: '#/parameters/apiVersionParameter'
      responses:
        '200':
          description: Successfully created or updated the container.
          schema:
            $ref: '#/definitions/Container'
        '202':
          description: Accepted the request to create or update the container.
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-long-running-operation: true
      x-ms-examples:
        ContainerPut:
          $ref: ./examples/ContainerPut.json
      description: Needs a more full description created.
    delete:
      tags:
      - Containers
      description: Deletes the container on the Data Box Edge/Data Box Gateway device.
      operationId: microsoftAzureContainersDelete
      parameters:
      - name: deviceName
        in: path
        description: The device name.
        required: true
        type: string
      - name: storageAccountName
        in: path
        description: The Storage Account Name
        required: true
        type: string
      - name: containerName
        in: path
        description: The container name.
        required: true
        type: string
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/resourceGroupNameParameter'
      - $ref: '#/parameters/apiVersionParameter'
      responses:
        '202':
          description: Accepted the request to delete the container.
        '204':
          description: The container is already deleted.
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-long-running-operation: true
      x-ms-examples:
        ContainerDelete:
          $ref: ./examples/ContainerDelete.json
      summary: Microsoft Azure Delete Subscriptions Subscriptionid Resourcegroups Resourcegroupname Providers Microsoft Databoxedge Databoxedgedevices Devicename Storageaccounts Storageaccountname Containers Containername
  ? /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataBoxEdge/dataBoxEdgeDevices/{deviceName}/storageAccounts/{storageAccountName}/containers/{containerName}/refresh
  : post:
      tags:
      - Containers
      summary: Microsoft Azure Refreshes The Container Metadata With The Data From The Cloud
      operationId: microsoftAzureContainersRefresh
      parameters:
      - name: deviceName
        in: path
        description: The device name.
        required: true
        type: string
      - name: storageAccountName
        in: path
        description: The Storage Account Name
        required: true
        type: string
      - name: containerName
        in: path
        description: The container name.
        required: true
        type: string
      - $ref: '#/parameters/subscriptionIdParameter'
      - $ref: '#/parameters/resourceGroupNameParameter'
      - $ref: '#/parameters/apiVersionParameter'
      responses:
        '200':
          description: Successfully refreshed the container on the device.
        '202':
          description: Accepted the request to refresh the container on the device.
        default:
          description: Error response describing why the operation failed.
          schema:
            $ref: '#/definitions/CloudError'
      x-ms-long-running-operation: true
      x-ms-examples:
        ContainerRefresh:
          $ref: ./examples/ContainerRefresh.json
      description: Needs a more full description created.
components:
  parameters:
    ContainerNameParameter:
      name: containerName
      in: path
      required: true
      description: The name of the container.
      schema:
        type: string
        minLength: 3
        maxLength: 63
        pattern: ^[a-z0-9](?:[a-z0-9]|-(?=[a-z0-9])){1,61}[a-z0-9]$
    DatabaseIdParameter:
      name: databaseId
      in: path
      required: true
      description: The ID of the database.
      schema:
        type: string
    ContainerIdParameter:
      name: containerId
      in: path
      required: true
      description: The ID of the container (collection).
      schema:
        type: string
    ContinuationParameter:
      name: x-ms-continuation
      in: header
      description: A continuation token returned from a previous request for pagination.
      schema:
        type: string
    ApiVersionParameter_2:
      name: x-ms-version
      in: header
      required: true
      description: The version of the Cosmos DB REST API.
      schema:
        type: string
        default: '2018-12-31'
    ApiVersionParameter:
      name: x-ms-version
      in: header
      required: true
      description: Specifies the version of the operation to use for this request.
      schema:
        type: string
        default: '2024-05-04'
    MaxItemCountParameter:
      name: x-ms-max-item-count
      in: header
      description: The maximum number of items to return per page. Default is 100, maximum is 1000.
      schema:
        type: integer
        default: 100
        maximum: 1000
  schemas:
    ErrorResponse:
      type: object
      description: Error response from Cosmos DB.
      properties:
        code:
          type: string
          description: The error code.
          example: example_value
        message:
          type: string
          description: The error message.
          example: example_value
      required:
      - code
      - message
    ContainerCreateRequest:
      type: object
      description: Request body for creating or replacing a container.
      properties:
        id:
          type: string
          description: The unique name that identifies the container.
          example: abc123
        indexingPolicy:
          $ref: '#/components/schemas/IndexingPolicy'
        partitionKey:
          $ref: '#/components/schemas/PartitionKeyDefinition'
        uniqueKeyPolicy:
          $ref: '#/components/schemas/UniqueKeyPolicy'
        conflictResolutionPolicy:
          $ref: '#/components/schemas/ConflictResolutionPolicy'
        defaultTtl:
          type: integer
          description: Default time-to-live in seconds.
          example: 10
      required:
      - id
      - partitionKey
    BlobItem:
      type: object
      description: A blob item in the enumeration results.
      properties:
        Name:
          type: string
          description: The name of the blob.
          example: Example Title
        Deleted:
          type: boolean
          description: Whether the blob is deleted.
          example: true
        Snapshot:
          type: string
          description: The snapshot DateTime.
          example: example_value
        VersionId:
          type: string
          description: The version ID of the blob.
          example: '500123'
        IsCurrentVersion:
          type: boolean
          description: Whether this is the current version.
          example: true
        Properties:
          $ref: '#/components/schemas/BlobProperties'
        Metadata:
          type: object
          additionalProperties:
            type: string
          description: The blob metadata.
          example: example_value
        Tags:
          type: object
          description: Blob tags.
          properties:
            TagSet:
              type: array
              items:
                type: object
                properties:
                  Key:
                    type: string
                  Value:
                    type: string
          example: example_value
      required:
      - Name
      - Properties
    ContainerListResult:
      type: object
      description: List of Cosmos DB containers.
      properties:
        _rid:
          type: string
          readOnly: true
          example: '500123'
        DocumentCollections:
          type: array
          items:
            $ref: '#/components/schemas/Container'
          description: List of containers.
          example: []
        _count:
          type: integer
          readOnly: true
          example: 10
    UniqueKeyPolicy:
      type: object
      description: The unique key policy configuration.
      properties:
        uniqueKeys:
          type: array
          items:
            type: object
            properties:
              paths:
                type: array
                items:
                  type: string
                description: Paths that must be unique.
          description: List of unique keys for the container.
          example: []
    IndexingPolicy:
      type: object
      description: The indexing policy for a container.
      properties:
        automatic:
          type: boolean
          default: true
          description: Whether indexing is automatic.
          example: true
        indexingMode:
          type: string
          enum:
          - consistent
          - lazy
          - none
          default: consistent
          description: The indexing mode.
          example: consistent
        includedPaths:
          type: array
          items:
            type: object
            properties:
              path:
                type: string
                description: The path to be indexed.
          description: Paths to include in indexing.
          example: []
        excludedPaths:
          type: array
          items:
            type: object
            properties:
              path:
                type: string
                description: The path to be excluded from indexing.
          description: Paths to exclude from indexing.
          example: []
        compositeIndexes:
          type: array
          items:
            type: array
            items:
              type: object
              properties:
                path:
                  type: string
                order:
                  type: string
                  enum:
                  - ascending
                  - descending
          description: Composite indexes for the container.
          example: []
        spatialIndexes:
          type: array
          items:
            type: object
            properties:
              path:
                type: string
              types:
                type: array
                items:
                  type: string
                  enum:
                  - Point
                  - Polygon
                  - MultiPolygon
                  - LineString
          description: Spatial indexes for the container.
          example: []
    BlobProperties:
      type: object
      description: Properties of a blob.
      properties:
        Creation-Time:
          type: string
          format: date-time-rfc1123
          description: The date/time the blob was created.
          example: example_value
        Last-Modified:
          type: string
          format: date-time-rfc1123
          description: The date/time the blob was last modified.
          example: example_value
        Etag:
          type: string
          description: The ETag of the blob.
          example: example_value
        Content-Length:
          type: integer
          format: int64
          description: The size of the blob in bytes.
          example: 10
        Content-Type:
          type: string
          description: The content type of the blob.
          example: example_value
        Content-Encoding:
          type: string
          description: The content encoding of the blob.
          example: example_value
        Content-Language:
          type: string
          description: The content language of the blob.
          example: example_value
        Content-MD5:
          type: string
          description: The MD5 hash of the blob content.
          example: example_value
        Content-Disposition:
          type: string
          description: The content disposition of the blob.
          example: example_value
        Cache-Control:
          type: string
          description: The cache control of the blob.
          example: example_value
        BlobType:
          type: string
          enum:
          - BlockBlob
          - PageBlob
          - AppendBlob
          description: The type of the blob.
          example: BlockBlob
        AccessTier:
          type: string
          enum:
          - Hot
          - Cool
          - Cold
          - Archive
          description: The access tier of the blob.
          example: Hot
        AccessTierInferred:
          type: boolean
          description: Whether the access tier was inferred.
          example: true
        LeaseStatus:
          type: string
          enum:
          - locked
          - unlocked
          description: The lease status.
          example: locked
        LeaseState:
          type: string
          enum:
          - available
          - leased
          - expired
          - breaking
          - broken
          description: The lease state.
          example: available
        ServerEncrypted:
          type: boolean
          description: Whether the blob data and metadata are encrypted.
          example: true
    ConflictResolutionPolicy:
      type: object
      description: The conflict resolution policy.
      properties:
        mode:
          type: string
          enum:
          - LastWriterWins
          - Custom
          default: LastWriterWins
          description: The conflict resolution mode.
          example: LastWriterWins
        conflictResolutionPath:
          type: string
          description: The path for the last-writer-wins conflict resolution.
          example: example_value
        conflictResolutionProcedure:
          type: string
          description: The stored procedure for custom conflict resolution.
          example: example_value
    Container:
      type: object
      description: A Cosmos DB container (collection) resource.
      properties:
        id:
          type: string
          description: The unique name that identifies the container.
          example: abc123
        indexingPolicy:
          $ref: '#/components/schemas/IndexingPolicy'
        partitionKey:
          $ref: '#/components/schemas/PartitionKeyDefinition'
        uniqueKeyPolicy:
          $ref: '#/components/schemas/UniqueKeyPolicy'
        conflictResolutionPolicy:
          $ref: '#/components/schemas/ConflictResolutionPolicy'
        defaultTtl:
          type: integer
          description: Default time-to-live in seconds. -1 means items never expire.
          example: 10
        _rid:
          type: string
          readOnly: true
          description: System-generated resource ID.
          example: '500123'
        _ts:
          type: integer
          readOnly: true
          description: System-generated timestamp.
          example: 10
        _self:
          type: string
          readOnly: true
          description: System-generated URI for the resource.
          example: example_value
        _etag:
          type: string
          readOnly: true
          description: System-generated resource etag.
          example: example_value
        _docs:
          type: string
          readOnly: true
          description: Addressable path for the documents resource.
          example: example_value
        _sprocs:
          type: string
          readOnly: true
          description: Addressable path for the stored procedures resource.
          example: example_value
        _triggers:
          type: string
          readOnly: true
          description: Addressable path for the triggers resource.
          example: example_value
        _udfs:
          type: string
          readOnly: true
          description: Addressable path for the user-defined functions resource.
          example: example_value
      required:
      - id
      - partitionKey
    StorageError:
      type: object
      description: Storage service error response.
      properties:
        Code:
          type: string
          description: The error code.
          example: example_value
        Message:
          type: string
          description: The error message.
          example: example_value
        AuthenticationErrorDetail:
          type: string
          description: Additional details for authentication errors.
          example: example_value
    BlobEnumerationResults:
      type: object
      description: An enumeration of blobs.
      properties:
        ServiceEndpoint:
          type: string
          description: The service endpoint URL.
          example: example_value
        ContainerName:
          type: string
          description: The name of the container.
          example: example_value
        Prefix:
          type: string
          description: The prefix used to filter results.
          example: example_value
        Marker:
          type: string
          description: The marker used for pagination.
          example: example_value
        MaxResults:
          type: integer
          description: The maximum number of results.
          example: 10
        Blobs:
          type: object
          properties:
            Blob:
              type: array
              items:
                $ref: '#/components/schemas/BlobItem'
            BlobPrefix:
              type: array
              items:
                type: object
                properties:
                  Name:
                    type: string
          example: example_value
        NextMarker:
          type: string
          description: The next marker for pagination.
          example: example_value
    PartitionKeyDefinition:
      type: object
      description: The partition key definition.
      properties:
        paths:
          type: array
          items:
            type: string
          description: List of paths using which data within the container can be partitioned.
          example: []
        kind:
          type: string
          enum:
          - Hash
          - Range
          - MultiHash
          default: Hash
          description: The algorithm used for partitioning.
          example: Hash
        version:
          type: integer
          enum:
          - 1
          - 2
          description: The version of the partition key definition.
          example: 1
      required:
      - paths
definitions:
  CloudErrorBody:
    description: An error response from the service.
    type: object
    properties:
      code:
        description: An identifier for the error. Codes are invariant and are intended to be consumed programmatically.
        type: string
      message:
        description: A message describing the error, intended to be suitable for display in a user interface.
        type: string
      details:
        description: A list of additional details about the error.
        type: array
        items:
          $ref: '#/definitions/CloudErrorBody'
        x-ms-identifiers: []
    x-ms-external: true
  ContainerProperties:
    description: The container properties.
    required:
    - dataFormat
    type: object
    properties:
      containerStatus:
        description: Current status of the container.
        enum:
        - OK
        - Offline
        - Unknown
        - Updating
        - NeedsAttention
        type: string
        readOnly: true
        x-ms-enum:
          name: ContainerStatus
          modelAsString: true
      dataFormat:
        description: DataFormat for Container
        enum:
        - BlockBlob
        - PageBlob
        - AzureFile
        type: string
        x-ms-enum:
          name: AzureContainerDataFormat
          modelAsString: true
      refreshDetails:
        $ref: '#/definitions/RefreshDetails'
        description: Details of the refresh job on this container.
        readOnly: true
      createdDateTime:
        format: date-time
        description: The UTC time when container got created.
        type: string
        readOnly: true
  ARMBaseModel:
    description: Represents the base class for all object models.
    type: object
    properties:
      id:
        description: The path ID that uniquely identifies the object.
        type: string
        readOnly: true
      name:
        description: The object name.
        type: string
        readOnly: true
      type:
        description: The hierarchical type of the object.
        type: string
        readOnly: true
    x-ms-azure-resource: true
  ContainerList:
    description: Collection of all the containers on the Data Box Edge/Gateway device.
    type: object
    properties:
      value:
        description: The list of containers.
        uniqueItems: false
        type: array
        items:
          $ref: '#/definitions/Container'
        x-ms-identifiers: []
        readOnly: true
      nextLink:
        description: Link to the next set of results.
        type: string
        readOnly: true
  Container:
    description: Represents a container on the  Data Box Edge/Gateway device.
    required:
    - properties
    type: object
    allOf:
    - $ref: '#/definitions/ARMBaseModel'
    properties:
      properties:
        $ref: '#/definitions/ContainerProperties'
        description: The container properties.
        x-ms-client-flatten: true
      systemData:
        $ref: ../../../../../common-types/resource-management/v2/types.json#/definitions/systemData
        description: Metadata pertaining to creation and last modification of Container
        readOnly: true
  CloudError:
    description: An error response from the service.
    type: object
    properties:
      error:
        $ref: '#/definitions/CloudErrorBody'
        description: The error details.
    x-ms-external: true
  RefreshDetails:
    description: Fields for tracking refresh job on the share or container.
    type: object
    properties:
      inProgressRefreshJobId:
        description: If a refresh job is currently in progress on this share or container, this field indicates the ARM resource ID of that job. The field is empty if no job is in progress.
        type: string
      lastCompletedRefreshJobTimeInUTC:
        format: date-time
        description: Indicates the completed time for the last refresh job on this particular share or container, if any.This could be a failed job or a successful job.
        type: string
      errorManifestFile:
        description: Indicates the relative path of the error xml for the last refresh job on this particular share or container, if any. This could be a failed job or a successful job.
        type: string
      lastJob:
        description: Indicates the id of the last refresh job on this particular share or container,if any. This could be a failed job or a successful job.
        type: string
parameters:
  resourceGroupNameParameter:
    name: resourceGroupName
    in: path
    description: The resource group name.
    required: true
    type: string
    x-ms-parameter-location: method
  apiVersionParameter:
    name: api-version
    in: query
    description: The API version.
    required: true
    type: string
  subscriptionIdParameter:
    name: subscriptionId
    in: path
    description: The subscription ID.
    required: true
    type: string
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/parameters/Endpoint'
