openapi: 3.2.0
info:
  title: Microsoft Azure Azure Container Registry Acr Manifest API
  description: Metadata API definition for the Azure Container Registry runtime
  version: 2019-07-15-preview
security:
- registry_auth: []
  registry_oauth2: []
tags:
- name: AcrManifest
  description: ACR APIs related to manifests
paths:
  /acr/v1/{name}/_manifests:
    get:
      tags:
      - AcrManifest
      description: List manifests of a repository
      operationId: microsoftAzureGetacrmanifests
      x-ms-examples:
        Get details of repository:
          $ref: ./examples/GetAcrManifests.json
      parameters:
      - $ref: '#/components/parameters/ImageName'
      - $ref: '#/components/parameters/QueryLast'
      - $ref: '#/components/parameters/QueryNum'
      - $ref: '#/components/parameters/QueryOrderBy'
      responses:
        '200':
          description: Returns a list of manifests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcrManifests'
        default:
          description: ACR error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcrErrors'
      summary: Microsoft Azure Get Acr Name Manifests
  /acr/v1/{name}/_manifests/{reference}:
    get:
      tags:
      - AcrManifest
      description: Get manifest attributes
      operationId: microsoftAzureGetacrmanifestattributes
      x-ms-examples:
        Get manifest attributes:
          $ref: ./examples/GetAcrManifestAttributes.json
      parameters:
      - $ref: '#/components/parameters/ImageName'
      - $ref: '#/components/parameters/ImageReference'
      responses:
        '200':
          description: List of attributes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcrManifestAttributes'
        default:
          description: ACR error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcrErrors'
      summary: Microsoft Azure Get Acr Name Manifests Reference
    patch:
      tags:
      - AcrManifest
      description: Update attributes of a manifest
      operationId: microsoftAzureUpdateacrmanifestattributes
      x-ms-examples:
        Update attributes of a manifest:
          $ref: ./examples/UpdateAcrManifestAttributes.json
      parameters:
      - $ref: '#/components/parameters/ImageName'
      - $ref: '#/components/parameters/ImageReference'
      - $ref: '#/components/parameters/RepoValue'
      responses:
        '200':
          description: The attributes are updated
        default:
          description: ACR error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcrErrors'
      summary: Microsoft Azure Patch Acr Name Manifests Reference
components:
  schemas:
    AcrErrorInfo:
      description: Error information
      properties:
        code:
          description: Error code
          type: string
        message:
          type: string
          description: Error message
        detail:
          type: object
          description: Error details
    ChangeableAttributes:
      properties:
        deleteEnabled:
          type: boolean
          description: Delete enabled
        writeEnabled:
          type: boolean
          description: Write enabled
        listEnabled:
          type: boolean
          description: List enabled
        readEnabled:
          type: boolean
          description: Read enabled
      example:
        readEnabled: true
        listEnabled: true
        deleteEnabled: true
        writeEnabled: true
    AcrManifestAttributes:
      description: Manifest attributes details
      properties:
        registry:
          description: Registry name
          type: string
        imageName:
          description: Image name
          type: string
        manifest:
          x-ms-client-name: ManifestAttributes
          description: Manifest attributes
          $ref: '#/components/schemas/AcrManifestAttributesBase'
      example:
        registry: acrapi.azurecr-test.io
        imageName: nanoserver
        manifest:
          digest: sha256:110d2b6c84592561338aa040b1b14b7ab81c2f9edbd564c2285dd7d70d777086
          imageSize: 2401606
          createdTime: '2018-09-06T06:17:20.9983915Z'
          lastUpdateTime: '2018-09-06T06:17:20.9983915Z'
          architecture: amd64
          os: windows
          mediaType: application/vnd.docker.distribution.manifest.v2+json
          configMediaType: application/vnd.docker.container.image.v1+json
          tags:
          - 4.7.2-20180905-nanoserver-1803
          changeableAttributes:
            deleteEnabled: true
            writeEnabled: true
            readEnabled: true
            listEnabled: true
    AcrManifests:
      description: Manifest attributes
      properties:
        registry:
          type: string
          description: Registry name
        imageName:
          type: string
          description: Image name
        manifests:
          x-ms-client-name: ManifestsAttributes
          type: array
          description: List of manifests
          items:
            $ref: '#/components/schemas/AcrManifestAttributesBase'
            description: Manifest details
      example:
        registry: registry
        imageName: imageName
        manifests:
        - changeableAttributes:
            quarantineDetails: quarantineDetails
            readEnabled: true
            quarantineState: quarantineState
            listEnabled: true
            deleteEnabled: true
            writeEnabled: true
          os: os
          digest: digest
          imageSize: 2401606
          createdTime: createdTime
          mediaType: mediaType
          configMediaType: configMediaType
          lastUpdateTime: lastUpdateTime
          architecture: architecture
          tags:
          - tags
          - tags
        - changeableAttributes:
            quarantineDetails: quarantineDetails
            readEnabled: true
            quarantineState: quarantineState
            listEnabled: true
            deleteEnabled: true
            writeEnabled: true
          os: os
          digest: digest
          imageSize: 2401606
          createdTime: createdTime
          mediaType: mediaType
          configMediaType: configMediaType
          lastUpdateTime: lastUpdateTime
          architecture: architecture
          tags:
          - tags
          - tags
    AcrErrors:
      description: Acr error response describing why the operation failed
      properties:
        errors:
          type: array
          description: Array of detailed error
          items:
            $ref: '#/components/schemas/AcrErrorInfo'
    AcrManifestAttributesBase:
      type: object
      description: Manifest details
      properties:
        digest:
          type: string
          description: Manifest
        imageSize:
          type: integer
          description: Image size
        createdTime:
          type: string
          description: Created time
        lastUpdateTime:
          type: string
          description: Last update time
        architecture:
          type: string
          description: CPU architecture
        os:
          type: string
          description: Operating system
        mediaType:
          type: string
          description: Media type
        configMediaType:
          type: string
          description: Config blob media type
        tags:
          type: array
          description: List of tags
          items:
            type: string
            description: Tag name
        changeableAttributes:
          $ref: '#/components/schemas/ChangeableAttributes'
          description: Changeable attributes
      example:
        changeableAttributes:
          readEnabled: true
          listEnabled: true
          deleteEnabled: true
          writeEnabled: true
        os: os
        digest: digest
        imageSize: 2401606
        createdTime: createdTime
        mediaType: mediaType
        configMediaType: configMediaType
        lastUpdateTime: lastUpdateTime
        architecture: architecture
        tags:
        - tags
        - tags
  parameters:
    ImageName:
      name: name
      in: path
      description: Name of the image (including the namespace)
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
    QueryNum:
      name: n
      in: query
      description: query parameter for max number of items
      required: false
      x-ms-parameter-location: method
      schema:
        type: integer
    QueryOrderBy:
      name: orderby
      in: query
      description: orderby query parameter
      required: false
      x-ms-parameter-location: method
      schema:
        type: string
    QueryLast:
      name: last
      in: query
      description: Query parameter for the last item in previous query. Result set will include values lexically after last.
      required: false
      x-ms-parameter-location: method
      schema:
        type: string
    RepoValue:
      name: value
      in: body
      description: Repository attribute value
      required: false
      schema:
        $ref: '#/components/schemas/ChangeableAttributes'
      x-ms-parameter-location: method
    ImageReference:
      name: reference
      in: path
      description: A tag or a digest, pointing to a specific image
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
  securitySchemes:
    registry_auth:
      type: http
      scheme: basic
    registry_oauth2:
      type: apiKey
      in: header
      name: Authorization
x-ms-parameterized-host:
  hostTemplate: '{url}'
  useSchemePrefix: false
  positionInOperation: first
  parameters:
  - $ref: '#/components/parameters/Url'
