openapi: 3.2.0
info:
  version: 2020-08-01-preview
  title: Microsoft Azure AccessControlClient AccessConnector Acr Tag API
  description: ACR APIs related to tags
servers:
- url: https://{registryName}.azurecr.io
  description: Azure Container Registry data plane endpoint
  variables:
    registryName:
      default: myregistry
      description: The name of the Azure Container Registry.
tags:
- name: AcrTag
  description: ACR APIs related to tags
paths:
  /acr/v1/{name}/_tags:
    get:
      tags:
      - AcrTag
      description: List tags of a repository
      operationId: microsoftAzureGetacrtags
      x-ms-examples:
        Get tags of a repository:
          $ref: ./examples/GetAcrTags.json
      parameters:
      - $ref: '#/components/parameters/ImageName'
      - $ref: '#/components/parameters/QueryLast'
      - $ref: '#/components/parameters/QueryNum'
      - $ref: '#/components/parameters/QueryOrderBy'
      - $ref: '#/components/parameters/QueryDigest'
      responses:
        '200':
          description: Tag details of a repository
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcrRepositoryTags'
        default:
          description: ACR error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcrErrors'
      summary: Microsoft Azure Get Acr Name Tags
  /acr/v1/{name}/_tags/{reference}:
    get:
      tags:
      - AcrTag
      description: Get tag attributes by tag
      operationId: microsoftAzureGetacrtagattributes
      x-ms-examples:
        Get tag attributes:
          $ref: ./examples/GetAcrTagAttributes.json
      parameters:
      - $ref: '#/components/parameters/ImageName'
      - $ref: '#/components/parameters/ManifestReference'
      responses:
        '200':
          description: Tag attributes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcrTagAttributes'
        default:
          description: ACR error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcrErrors'
      summary: Microsoft Azure Get Acr Name Tags Reference
    patch:
      tags:
      - AcrTag
      description: Update tag attributes
      operationId: microsoftAzureUpdateacrtagattributes
      x-ms-examples:
        Update attributes of a manifest:
          $ref: ./examples/UpdateAcrTagAttributes.json
      parameters:
      - $ref: '#/components/parameters/ImageName'
      - $ref: '#/components/parameters/ManifestReference'
      - $ref: '#/components/parameters/RepoValue'
      responses:
        '200':
          description: The attributes are updated
        default:
          description: ACR error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcrErrors'
      summary: Microsoft Azure Patch Acr Name Tags Reference
    delete:
      tags:
      - AcrTag
      description: Delete tag
      operationId: microsoftAzureDeleteacrtag
      x-ms-examples:
        Update attributes of a manifest:
          $ref: ./examples/DeleteAcrTag.json
      parameters:
      - $ref: '#/components/parameters/ImageName'
      - $ref: '#/components/parameters/ManifestReference'
      responses:
        '202':
          description: The tag is deleted
        default:
          description: ACR error response describing why the operation failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcrErrors'
      summary: Microsoft Azure Delete Acr Name Tags Reference
components:
  parameters:
    QueryOrderBy:
      name: orderby
      in: query
      description: orderby query parameter
      required: false
      x-ms-parameter-location: method
      schema:
        type: string
    ImageName:
      name: name
      in: path
      description: Name of the image (including the namespace)
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
    ManifestReference:
      name: reference
      in: path
      description: Tag or digest of the target manifest
      required: true
      x-ms-parameter-location: method
      schema:
        type: string
    QueryLast:
      name: last
      in: query
      description: Query parameter for the last item in previous query. Result set will include values lexically after last.
      required: false
      x-ms-parameter-location: method
      schema:
        type: string
    QueryDigest:
      name: digest
      in: query
      description: filter by digest
      required: false
      x-ms-parameter-location: method
      schema:
        type: string
    RepoValue:
      name: value
      in: body
      description: Repository attribute value
      required: false
      schema:
        $ref: '#/components/schemas/ChangeableAttributes'
      x-ms-parameter-location: method
    QueryNum:
      name: n
      in: query
      description: query parameter for max number of items
      required: false
      x-ms-parameter-location: method
      schema:
        type: integer
  schemas:
    AcrRepositoryTags:
      description: List of tag details
      properties:
        registry:
          type: string
          description: Registry name
        imageName:
          type: string
          description: Image name
        tags:
          type: array
          x-ms-client-name: TagsAttributes
          description: List of tag attribute details
          items:
            $ref: '#/components/schemas/AcrTagAttributesBase'
      example:
        registry: registry
        imageName: imageName
        tags:
        - changeableAttributes:
            readEnabled: true
            listEnabled: true
            deleteEnabled: true
            writeEnabled: true
          name: name
          digest: digest
          createdTime: createdTime
          signed: true
          lastUpdateTime: lastUpdateTime
        - changeableAttributes:
            readEnabled: true
            listEnabled: true
            deleteEnabled: true
            writeEnabled: true
          name: name
          digest: digest
          createdTime: createdTime
          signed: true
          lastUpdateTime: lastUpdateTime
    ChangeableAttributes:
      properties:
        deleteEnabled:
          type: boolean
          description: Delete enabled
        writeEnabled:
          type: boolean
          description: Write enabled
        listEnabled:
          type: boolean
          description: List enabled
        readEnabled:
          type: boolean
          description: Read enabled
      example:
        readEnabled: true
        listEnabled: true
        deleteEnabled: true
        writeEnabled: true
    AcrTagAttributesBase:
      description: Tag attribute details
      properties:
        name:
          type: string
          description: Tag name
        digest:
          type: string
          description: Tag digest
        createdTime:
          type: string
          description: Tag created time
        lastUpdateTime:
          type: string
          description: Tag last update time
        signed:
          type: boolean
          description: Is signed
        changeableAttributes:
          $ref: '#/components/schemas/ChangeableAttributes'
          description: Changeable attributes
      example:
        changeableAttributes:
          readEnabled: true
          listEnabled: true
          deleteEnabled: true
          writeEnabled: true
        name: tagname
        digest: sha256:0873c923e00e0fd2ba78041bfb64a105e1ecb7678916d1f7776311e45bf5634b
        createdTime: '2018-08-10T17:28:44.1082945Z'
        signed: true
        lastUpdateTime: '2018-08-10T17:28:44.1082945Z'
    AcrErrors:
      description: Acr error response describing why the operation failed
      properties:
        errors:
          type: array
          description: Array of detailed error
          items:
            $ref: '#/components/schemas/AcrErrorInfo'
    AcrErrorInfo:
      description: Error information
      properties:
        code:
          description: Error code
          type: string
        message:
          type: string
          description: Error message
        detail:
          type: object
          description: Error details
    AcrTagAttributes:
      description: Tag attributes
      properties:
        registry:
          type: string
          description: Registry name
        imageName:
          type: string
          description: Image name
        tag:
          x-ms-client-name: TagAttributes
          description: List of tag attribute details
          $ref: '#/components/schemas/AcrTagAttributesBase'
      example:
        registry: registry
        imageName: imageName
        tag:
          changeableAttributes:
            readEnabled: true
            listEnabled: true
            deleteEnabled: true
            writeEnabled: true
          name: name
          digest: digest
          createdTime: createdTime
          signed: true
          lastUpdateTime: lastUpdateTime
x-ms-parameterized-host:
  hostTemplate: '{endpoint}'
  useSchemePrefix: false
  parameters:
  - $ref: '#/components/parameters/Endpoint'
